name: ci-smoke

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OK
        run: echo ok
